export const NODE_ENV_DEVELOPMENT = 'development'
export const NODE_ENV_PRODUCTION = 'production'
export const REQ_SUCCESS = 200
export const REQ_BAD_REQUEST = 400
export const REQ_NOT_FOUND = 404
export const REQ_INTERNAL_SERVER_ERROR = 500
export const UPDATE_MESSAGE = 'Başarıyla Güncellendi'
export const ADD_MESSAGE = 'Başarıyla Eklendi'
export const DELETE_MESSAGE = 'Başarıyla Silindi'
export const NOT_FOUND = 'Kayıt Bulunmamaktadır'