# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: socialMediaPostgresDb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: socialMedia
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - 5433:5432